spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowCredentials: true
                allowedHeaders: '[*]'
                allowedMethods: '[GET, POST, PUT, PATCH, DELETE, OPTIONS]'
                allowedOrigins: '[http://localhost:5173]'
                exposedHeaders: '[Authorization, Set-Cookie]'
                maxAge: 3600
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true