spring:
  application:
    name: location-telemetry-tracking-service

  config:
    import: optional:configserver:http://localhost:8888/

jwt-secret: chukibimatdetaorachuoitokenphaidudaineukhongsebinemloi
