plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}
ext {
    springCloudVersion = "2025.1.3"
}

group = 'SpringBootRestAPI'
version = '0.0.1-SNAPSHOT'
description = 'websocket-gateway-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // 1. WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // 2. Eureka Client (Đăng ký service)
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // 3. Kafka (Truyền nhận stream tọa độ)
    implementation 'org.springframework.kafka:spring-kafka'

    // 4. Security & JWT (Xác thực kết nối socket)
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Lưu ý: Nếu xử lý JWT Token, bạn nên thêm thư viện JJWT dưới đây:
    // Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api
    implementation("io.jsonwebtoken:jjwt-api:0.13.0")
    // Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.13.0")
    // Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.13.0")
    // 5. Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'


    implementation 'org.springframework.cloud:spring-cloud-starter-config'


    // DevTools & Testing
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
